[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 10

[browser]
gatherUsageStats = false

[theme]
base = "dark"

[client]
showErrorDetails = false
toolbarMode = "minimal"
